version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-embeddings
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_HOST=0.0.0.0
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    command: serve

  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n-embeddings
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_LOG_LEVEL=debug
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY=n8n-embedding-test-key
      - N8N_USER_FOLDER=/home/node/.n8n/custom
      - NODE_FUNCTION_ALLOW_EXTERNAL=@langchain/core
      - NODE_ENV=development
      # Ollama connection
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_HOST=ollama
    volumes:
      - ./data/n8n:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/dist
      - ./package.json:/home/node/.n8n/custom/package.json:ro
    networks:
      - n8n-network
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

networks:
  n8n-network:
    driver: bridge