name: Publish to NPM

on:
  push:
    branches:
      - master
      - main
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type to publish (patch/minor/major)'
        required: false
        default: 'patch'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run linter
        run: npm run lint || true

      - name: Build
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi
          echo "Build successful, dist directory contents:"
          ls -la dist/

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Determine version bump
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION_TYPE="${{ github.event.inputs.version }}"
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION_TYPE="minor"
          else
            # Check commit message for version hints
            COMMIT_MSG=$(git log -1 --pretty=%B)
            if [[ $COMMIT_MSG == *"BREAKING CHANGE"* ]] || [[ $COMMIT_MSG == *"major:"* ]]; then
              VERSION_TYPE="major"
            elif [[ $COMMIT_MSG == *"feat:"* ]] || [[ $COMMIT_MSG == *"feature:"* ]]; then
              VERSION_TYPE="minor"
            else
              VERSION_TYPE="patch"
            fi
          fi
          echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          npm version ${{ steps.version.outputs.version_type }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git tag
        if: success()
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new_version }} [skip ci]"
          git tag v${{ steps.bump.outputs.new_version }}
          git push origin HEAD:${{ github.ref_name }}
          git push origin v${{ steps.bump.outputs.new_version }}

      - name: Create GitHub Release
        if: success() && github.event_name != 'release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          release_name: Release v${{ steps.bump.outputs.new_version }}
          body: |
            ## 🚀 n8n-nodes-qwen-embedding v${{ steps.bump.outputs.new_version }}

            ### Installation
            ```bash
            npm install n8n-nodes-qwen-embedding
            ```

            ### What's Changed
            See commit history for detailed changes.

            ### Full Changelog
            https://github.com/${{ github.repository }}/compare/v${{ steps.bump.outputs.new_version }}...HEAD
          draft: false
          prerelease: false